spring.application.name=guiaFinanceiro
spring.profiles.active=prod
# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create

spring.jpa.generate-ddl=true

spring.flyway.enabled=false

# Força o Hibernate a não usar o CAST problemático em UUIDs
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

